import type { AnalyticsOverview } from '@/lib/types';

export const DEFAULT_ANALYTICS: AnalyticsOverview = {
  period: 'Last 30 Days',
  total_sessions: 142580,
  total_users: 118920,
  total_pageviews: 318450,
  bounce_rate: 41.2,
  avg_session_duration: '2m 48s',
  ga4_measurement_id: 'G-LV892B193K',
  gsc_property: 'https://blog.loveable.us',
  last_updated: new Date().toISOString(),
  channels: [
    {
      channel: 'Organic Search (Google)',
      sessions: 91536,
      users: 78400,
      bounce_rate: 38.4,
      avg_duration_sec: 192,
      conversion_rate: 4.8,
      percentage: 64.2,
      color: '#16a34a',
    },
    {
      channel: 'Direct Navigation',
      sessions: 26377,
      users: 21200,
      bounce_rate: 45.1,
      avg_duration_sec: 130,
      conversion_rate: 3.9,
      percentage: 18.5,
      color: '#2563eb',
    },
    {
      channel: 'Social (Pinterest & Instagram)',
      sessions: 16824,
      users: 14100,
      bounce_rate: 42.0,
      avg_duration_sec: 155,
      conversion_rate: 5.2,
      percentage: 11.8,
      color: '#ec4899',
    },
    {
      channel: 'Referral & Backlinks',
      sessions: 5845,
      users: 4900,
      bounce_rate: 39.5,
      avg_duration_sec: 170,
      conversion_rate: 4.4,
      percentage: 4.1,
      color: '#f97316',
    },
    {
      channel: 'Email / Newsletter',
      sessions: 1998,
      users: 1820,
      bounce_rate: 32.1,
      avg_duration_sec: 245,
      conversion_rate: 6.8,
      percentage: 1.4,
      color: '#eab308',
    },
  ],
  top_landing_pages: [
    {
      path: '/regalos-1-ano-noviazgo/',
      title: '36 Mejores Regalos de 1 Año de Noviazgo',
      pageviews: 28450,
      unique_visitors: 22100,
      outbound_clicks: 1380,
      ctr: 6.24,
    },
    {
      path: '/regalos-bodas-de-madera/',
      title: '54 Mejores Regalos de Bodas de Madera (5º Aniversario)',
      pageviews: 24900,
      unique_visitors: 19400,
      outbound_clicks: 1195,
      ctr: 6.16,
    },
    {
      path: '/regalos-cumpleanos-para-mama/',
      title: '35 Mejores Regalos de Cumpleaños para Mamá',
      pageviews: 21200,
      unique_visitors: 16800,
      outbound_clicks: 980,
      ctr: 5.83,
    },
    {
      path: '/regalos-san-valentin-para-el/',
      title: 'San Valentín para Él: 15 Regalos Románticos',
      pageviews: 19800,
      unique_visitors: 15300,
      outbound_clicks: 920,
      ctr: 6.01,
    },
    {
      path: '/regalos/aniversario/',
      title: 'Catálogo de Regalos de Aniversario',
      pageviews: 18400,
      unique_visitors: 14200,
      outbound_clicks: 810,
      ctr: 5.70,
    },
    {
      path: '/regalos-cumpleanos-para-papa/',
      title: '55 Mejores Regalos de Cumpleaños para Papá',
      pageviews: 16900,
      unique_visitors: 13100,
      outbound_clicks: 745,
      ctr: 5.69,
    },
  ],
  device_split: [
    { device: 'Mobile', percentage: 74.2 },
    { device: 'Desktop', percentage: 21.8 },
    { device: 'Tablet', percentage: 4.0 },
  ],
  geo_split: [
    { country: 'España', flag: '🇪🇸', percentage: 68.5, users: 81460 },
    { country: 'México', flag: '🇲🇽', percentage: 14.2, users: 16880 },
    { country: 'Estados Unidos', flag: '🇺🇸', percentage: 7.8, users: 9270 },
    { country: 'Argentina', flag: '🇦🇷', percentage: 4.5, users: 5350 },
    { country: 'Colombia', flag: '🇨🇴', percentage: 3.2, users: 3800 },
    { country: 'Otros países', flag: '🌍', percentage: 1.8, users: 2160 },
  ],
};
