import type { AnalyticsOverview } from '@/lib/types';

export const DEFAULT_ANALYTICS: AnalyticsOverview = {
  period: 'Tiempo real / Últimos 30 días',
  total_sessions: 0,
  total_users: 0,
  total_pageviews: 0,
  bounce_rate: 0,
  avg_session_duration: '0m 00s',
  ga4_measurement_id: 'G-WRGWXTNWV3',
  gsc_property: 'https://www.miregalo.us/',
  last_updated: new Date().toISOString(),
  channels: [
    {
      channel: 'Organic Search (Google)',
      sessions: 0,
      users: 0,
      bounce_rate: 0,
      avg_duration_sec: 0,
      conversion_rate: 0,
      percentage: 0,
      color: '#16a34a',
    },
    {
      channel: 'Direct Navigation',
      sessions: 0,
      users: 0,
      bounce_rate: 0,
      avg_duration_sec: 0,
      conversion_rate: 0,
      percentage: 0,
      color: '#2563eb',
    },
    {
      channel: 'Social (Pinterest & Instagram)',
      sessions: 0,
      users: 0,
      bounce_rate: 0,
      avg_duration_sec: 0,
      conversion_rate: 0,
      percentage: 0,
      color: '#ec4899',
    },
    {
      channel: 'Referral & Backlinks',
      sessions: 0,
      users: 0,
      bounce_rate: 0,
      avg_duration_sec: 0,
      conversion_rate: 0,
      percentage: 0,
      color: '#f97316',
    },
    {
      channel: 'Email / Newsletter',
      sessions: 0,
      users: 0,
      bounce_rate: 0,
      avg_duration_sec: 0,
      conversion_rate: 0,
      percentage: 0,
      color: '#eab308',
    },
  ],
  top_landing_pages: [
    {
      path: '/',
      title: 'Portada Principal | Mi Regalo',
      pageviews: 0,
      unique_visitors: 0,
      outbound_clicks: 0,
      ctr: 0,
    },
    {
      path: '/regalos/',
      title: 'Todas las Guías de Regalos',
      pageviews: 0,
      unique_visitors: 0,
      outbound_clicks: 0,
      ctr: 0,
    },
    {
      path: '/blog/',
      title: 'Explorar Artículos de Blog',
      pageviews: 0,
      unique_visitors: 0,
      outbound_clicks: 0,
      ctr: 0,
    },
    {
      path: '/aniversario/',
      title: 'Regalos para Aniversario',
      pageviews: 0,
      unique_visitors: 0,
      outbound_clicks: 0,
      ctr: 0,
    },
    {
      path: '/cumpleanos/',
      title: 'Regalos para Cumpleaños',
      pageviews: 0,
      unique_visitors: 0,
      outbound_clicks: 0,
      ctr: 0,
    },
    {
      path: '/fiestas/',
      title: 'Fiestas y Tradiciones',
      pageviews: 0,
      unique_visitors: 0,
      outbound_clicks: 0,
      ctr: 0,
    },
  ],
  device_split: [
    { device: 'Mobile', percentage: 0 },
    { device: 'Desktop', percentage: 0 },
    { device: 'Tablet', percentage: 0 },
  ],
  geo_split: [
    { country: 'España', flag: '🇪🇸', users: 0, percentage: 0 },
    { country: 'México', flag: '🇲🇽', users: 0, percentage: 0 },
    { country: 'Estados Unidos', flag: '🇺🇸', users: 0, percentage: 0 },
    { country: 'Argentina', flag: '🇦🇷', users: 0, percentage: 0 },
    { country: 'Colombia', flag: '🇨🇴', users: 0, percentage: 0 },
    { country: 'Otros países', flag: '🌍', users: 0, percentage: 0 },
  ],
};
