import type { SiteSettings } from '@/lib/types';

/** Default settings – every value is editable in /admin/settings. */
export const DEFAULT_SETTINGS: SiteSettings = {
  site_name: 'Miregalo',
  site_tagline: 'Ideas de regalos significativas para cada persona, relación y ocasión.',
  site_description: 'Guías y sugerencias de regalos pensadas para sorprender a quien más quieres en cualquier momento especial.',
  organization_name: 'Miregalo',
  organization_url: 'https://www.miregalo.us',
  logo_url: '/images/miregalo-logo.png',
  logo_fullsize_url: '/images/miregalo-logo-fullsize.png',
  favicon_url: '/favicon.png',
  default_og_image: '/images/miregalo-logo-fullsize.png',
  locale: 'es',
  title_separator: '|',
  shop_url: '/regalos/',
  shop_label: 'Explorar Regalos',
  contact_url: '/contacto/',
  copyright: '© {year} Miregalo. Todos los derechos reservados.',
  footer_tagline: 'Ideas desde el corazón, hechas para compartir.',
  footer_about: 'Miregalo es tu portal de referencia para encontrar regalos originales, personalizados y emotivos para cada ocasión especial.',
  hero_eyebrow: 'Ideas con significado, hechas personales',
  hero_title: 'Encuentra un regalo que recordarán siempre',
  hero_lead:
    'Explora guías detalladas para cada persona, relación y ocasión, y transforma la idea perfecta en un recuerdo inolvidable.',
  search_placeholder: 'Buscar ideas de regalos, personas u ocasiones...',
  cta_eyebrow: 'Hazlo personal',
  cta_title: '¿Encontraste la idea perfecta?',
  cta_text: 'Convierte tu inspiración en un regalo personalizado creado especialmente para ellos.',
  affiliate_disclosure:
    'Este artículo contiene recomendaciones editoriales independientes. Si compras a través de nuestros enlaces, podemos recibir una pequeña comisión sin coste adicional para ti. En calidad de Afiliado de Amazon, obtengo ingresos por las compras adscritas que cumplen los requisitos aplicables.',
  posts_per_page: 24,
  ga4_id: '',
  gsc_verification: '',
  gsc_property: '',
  bing_verification: '',
  pinterest_verification: '',
  pinterest_tag_id: '',
  head_scripts: '',
  body_scripts: '',
  robots_extra: '',
  noindex_site: false,
  google_search_cx: '',
  amazon_associates_tag: 'miregalo26-20',
  awin_affiliate_id: '128945',
  ebay_campaign_id: '5338901234',
  walmart_partner_id: 'wm-giftblog-987',
  default_affiliate_strategy: 'smart_distribution',
};
